### ISSUE TITLE
PolarCV - "Mult" value changes when re-opening patch

### ISSUE THREAD

**Issue by Loop-s** [aaronkarp123/EarthTones#4]
Hi! Giving your PolarCV module a try and found the following issue:

Create a new patch with either one or multiple instances (the issue seems to be occurring either way) of PolarCV and modify the "Mult" parameter. Here's an example I captured prior to closing the patch: 

![earthtones - polarcv 01](https://user-images.githubusercontent.com/110244461/209015874-57afa6d2-4733-4740-b322-3cbf10fec267.png)

As you can see, for the "Mult" values, the top-left module is yellow and the bottom two are pink and yellow.

Now, after closing VCV Rack and re-opening the same patch, the "Mult" values are not the same:

![earthtones - polarcv 02](https://user-images.githubusercontent.com/110244461/209016542-dbe6832c-04f5-4f59-84a7-0d86316fb742.png)

We are now looking at pink, blue and pink instead of yellow, pink and yellow.

This was captured on Windows 10 64-bit.

Let me know if you need any more info.

Thanks and great module!

Cheers,
Loops

**Comment by aaronkarp123** [comment]
Hi Loops,

Thanks for catching this! The current-time-multiplier value wasn't being stored as a parameter, so it was being reset on opening the program. I have updated it with [this commit](https://github.com/aaronkarp123/EarthTones/commit/6b34e199d95417527671755e02af5dbe3b226333), and have requested the module be updated with this and two other day-one bugs.

Thanks for letting me know about this issue, and I hope you enjoy the module!

Best,
Aaron

**Comment by Loop-s** [comment]
No problem Aaron, glad to see it was a quick fix.
